name: r_env
channels:
      - conda-forge
      - bioconda
dependencies:
      - r-base=4.3.0
      - r-devtools
      - r-argparse
      - r-ggplot2
      - r-gggenes
      - bioconductor-bsgenome
      - bioconductor-genomicalignments
      - bioconductor-trackviewer
      - bioconductor-biomart
      - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
      - bioconductor-org.hs.eg.db
      - bioconductor-ensembldb
      - bioconductor-EnsDb.Hsapiens.v75
