name: r_env
channels:
    - conda-forge
    - bioconda
dependencies:
    - r-base=4.3.0
    - r-devtools
    - r-argparse
    - r-remotes
    - r-rcpp
    - r-ggplot2
    - r-ggnewscale
    - r-gggenes
    - bioconductor-bsgenome
    - bioconductor-genomicalignments
    - r-randomcolor
