name: Build and Push Docker Images with Version Tags

on:
  push:
    branches:
      - main

env:
  ORG_NAME: eichlerlab

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Find changed Dockerfiles and Extract Versions
      id: dockerfiles
      run: |
        set +e
        CHANGED_FILES_TMP=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Dockerfile$')
        set -e
        for CHANGED_FILE in $CHANGED_FILES;do
          if [[ ! -z "CHANGED_FILE "]]; then
            CHANGED_FILES="$CHANGED_FILE $CHANGED_FILES"
          fi
        done
        if [[ "$CHANGE_FILES" = ""]];then
          echo "CHANGED=false" >> $GITHUB_ENV
          echo "No Dockerfiles changes detected."
          exit 0
        else
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "CHANGED=true" >> $GITHUB_ENV
          echo "Changed Dockerfiles: $CHANGED_FILES"
        fi

    - name: Log in to Docker Hub
      if: env.CHANGED == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_1 }}
        password: ${{ secrets.DOCKER_USER_1_PAT }}

    - name: Build and push Docker images
      if: env.CHANGED == 'true'
      run: |
        CHANGED_FILES="${{ env.CHANGED_FILES }}"
        for file in $CHANGED_FILES; do
          IFS='/' read -ra ADDR <<< "$file"
          SOFTWARE="${ADDR[0]}"
          VERSION="${ADDR[1]}"
          IMAGE_PATH="${SOFTWARE}/${VERSION}"
          docker build -t ${{ env.ORG_NAME }}/${SOFTWARE}:${VERSION} $IMAGE_PATH
          echo "Pushing ${{ env.ORG_NAME }}/${SOFTWARE}:${VERSION}"
          docker push ${{ env.ORG_NAME }}/${SOFTWARE}:${VERSION}
        done